from django.conf.urls import url
from web import views_home

urlpatterns = [
    url(r'^$', views_home.home, name='home'),
    url(r'^particlepicking/$', views_home.particlepicking, name='particlepicking'),
    url(r'^ctfdetection/$', views_home.ctfdetection, name='ctfdetection'),
    url(r'^resolutionenhancement/$', views_home.resolutionenhancement, name='resolutionenhancement'),
    url(r'^particlepicking/results/$', views_home.particlepickingresults, name='particlepickingresults'),
    url(r'^ctfdetection/results/$', views_home.ctfdetectionresults, name='ctfdetectionresults'),
    url(r'^ctfdetection/results/206.html', views_home.ctfdetectionresults206, name='ctfdetectionresults206'),
    url(r'^ctfdetection/results/207.html', views_home.ctfdetectionresults207, name='ctfdetectionresults207'),
    url(r'^ctfdetection/results/250.html', views_home.ctfdetectionresults250, name='ctfdetectionresults250'),
    url(r'^ctfdetection/results/256.html', views_home.ctfdetectionresults256, name='ctfdetectionresults256'),
    url(r'^ctfdetection/results/257.html', views_home.ctfdetectionresults257, name='ctfdetectionresults257'),
    url(r'^ctfdetection/results/282.html', views_home.ctfdetectionresults282, name='ctfdetectionresults282'),
    url(r'^ctfdetection/results/287.html', views_home.ctfdetectionresults287, name='ctfdetectionresults287'),
    url(r'^ctfdetection/results/291.html', views_home.ctfdetectionresults291, name='ctfdetectionresults291'),
    url(r'^ctfdetection/results/292.html', views_home.ctfdetectionresults292, name='ctfdetectionresults292'),
    url(r'^ctfdetection/results/296.html', views_home.ctfdetectionresults296, name='ctfdetectionresults296'),
    url(r'^ctfdetection/results/297.html', views_home.ctfdetectionresults297, name='ctfdetectionresults297'),
    url(r'^ctfdetection/results/298.html', views_home.ctfdetectionresults298, name='ctfdetectionresults298'),
    url(r'^ctfdetection/results/299.html', views_home.ctfdetectionresults299, name='ctfdetectionresults299'),
    url(r'^ctfdetection/results/300.html', views_home.ctfdetectionresults300, name='ctfdetectionresults300'),
    url(r'^ctfdetection/results/301.html', views_home.ctfdetectionresults301, name='ctfdetectionresults301'),
    url(r'^ctfdetection/results/303.html', views_home.ctfdetectionresults303, name='ctfdetectionresults303'),
    url(r'^ctfdetection/results/304.html', views_home.ctfdetectionresults304, name='ctfdetectionresults304'),
    url(r'^ctfdetection/results/310.html', views_home.ctfdetectionresults310, name='ctfdetectionresults310'),
    url(r'^ctfdetection/results/312.html', views_home.ctfdetectionresults312, name='ctfdetectionresults312'),
    url(r'^ctfdetection/results/314.html', views_home.ctfdetectionresults314, name='ctfdetectionresults314'),
    url(r'^ctfdetection/results/318.html', views_home.ctfdetectionresults318, name='ctfdetectionresults318'),
    url(r'^ctfdetection/results/336.html', views_home.ctfdetectionresults336, name='ctfdetectionresults336'),
    url(r'^ctfdetection/results/337.html', views_home.ctfdetectionresults337, name='ctfdetectionresults337'),
    url(r'^ctfdetection/results/339.html', views_home.ctfdetectionresults339, name='ctfdetectionresults339'),
    url(r'^ctfdetection/results/340.html', views_home.ctfdetectionresults340, name='ctfdetectionresults340'),
    url(r'^ctfdetection/results/341.html', views_home.ctfdetectionresults341, name='ctfdetectionresults341'),
    url(r'^ctfdetection/results/342.html', views_home.ctfdetectionresults342, name='ctfdetectionresults342'),
    url(r'^ctfdetection/results/344.html', views_home.ctfdetectionresults344, name='ctfdetectionresults344'),
    url(r'^ctfdetection/datasets/$', views_home.ctfdetectiondatasets, name='ctfdetectiondatasets'),
]
